Task_1_2_2
Allody22/OOP_JAVA pull request #18
Opened 2022-10-13 16:00 UTC by Allody22

It will be good pull request

2022-10-16 10:11 UTC, Allody22 commented
Вообще очень много пул реквестов было потрачено, чтобы в файлс ченджед всё было нормально. Эта ошибка возникает как-то случайно и пофиксилось просто после огромного количества пересозданий ветки и пул реквестов. Сейчас, надеюсь, всё нормально (Sorry for russian language)

2022-10-16 10:45 UTC, shadrina requested changes
В остальном ок

2022-10-16 10:45 UTC, shadrina commented on Task_1_2_2/src/main/java/ru/nsu/mbogdanov2/DepthFirstSearchIterator.java
> +        throw new ConcurrentModificationException();
Интерфейс итератор предоставляет этот метод как раз, чтобы дать возможность пользователю удалять элемент во время итерирования. Например, тебе надо удалить элемент по какому-то условию -- ты итерируешься по коллекции, проверяешь каждый элемент, находишь нужный, удаляешь его с помощью этого метода. `ConcurrentModificationException` нужен тогда, когда саму коллекцию изменили без ведома итератора, то есть сделали напрямую удаление или добавление.

2022-10-16 10:45 UTC, shadrina commented on Task_1_2_2/src/main/java/ru/nsu/mbogdanov2/DepthFirstSearchIterator.java
> +        throw new ConcurrentModificationException();
Как это сделать идеально: https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/java/util/ArrayList.java#L780

Что тут происходит: на каждой операции изменения коллекции сама коллекция увеличивает счетчик `modCount`, а итератор следит, что после его инициализации этот счетчик не изменился. И если изменился, он кидает исключение.

2022-10-16 10:45 UTC, shadrina commented on Task_1_2_2/src/main/java/ru/nsu/mbogdanov2/DepthFirstSearchIterator.java
> +        throw new ConcurrentModificationException();
Если непонятно, подойдешь на паре. Если понятно, поправь этот момент. Необязательно делать как в ArrayList, но исключение должно кидаться по теме.

2022-10-18 04:08 UTC, Allody22 commented
Ну я сделал счётчик элементов, который прибавляю к корню, который нахожу с помощью функции. Не хотелось полностью переделывать филды своего дерева и отдельно как-то запоминать корень, поэтому ищу его с помощью довольно простой функции.  У Артёма метода remove вообще почему-то нет в итераторе, даже не знаю правильно ли это. На данный момент оставлю этот код так, но просто добавить проверку на изменения модификаций дерева в базовый метод remove, который предлагается джавой, не сложно. Может, сделаю через пару часов, если я всё правильно понял (или, может вы сегодня ответите, правильно ли я всё понял)

2022-10-18 07:13 UTC, shadrina reviewed
Понял правильно, только я не вижу тестов, по которым можно было бы убедиться, что ConcurrentModificationException кидается тогда, когда надо, и не кидается тогда, когда не надо. remove() переопределять необязательно, но будешь молодец, если переопределишь. Необязательно, потому что у него есть дефолтная реализация в интерфейсе (модификатор default позволяет написать дефолтную реализацию метода интерфейса)

2022-10-18 09:12 UTC, Allody22 commented
Так, ну у меня ведь есть обход по дереву с помощью итератора, никаких ConcurrentModificationException там не возникает, а это ведь и означает, что когда в нормальной ситуации это исключение не вылазит. Сейчас добавлю проверку на ситуации, когда исключение вылезает, это не сложно

2022-10-18 09:49 UTC, Allody22 commented
Добавил тесты, что исключения не вылезают, когда не надо, что исключения вылезают, когда надо.  Ну, кажется, все что надо сделал

2022-10-18 13:07 UTC, Allody22 commented
Еще кстати вопрос возникает. Гитхаб создан для контроля версий, но стоит ли заливать максимально сырой код (мб какие-то наброски) на гитхаб сразу и пул реквестить или лучше сначала локально с этим разбираться. Пока исправлял это, хотел вспомнить одну идею которая была в самом начале, но понял, что это было так давно, что в тот момент я даже ветку еще не создал. То есть в какой момент готовности кода мы создаем ветку/пул реквест?

2022-10-19 06:11 UTC, shadrina commented on Task_1_2_2/src/test/java/ru/nsu/mbogdanov2/BreadthFirstSearchTests.java
> +        ArrayList<Integer> actualSearchList = new ArrayList<>();
```List<Integer> actualSearchList = new ArrayList<>();```

!!

2022-10-19 06:38 UTC, Allody22 commented
Everything is done and questions about **final**  are answered

2022-10-19 07:29 UTC, merged