Task_1_2_3
Allody22/OOP_JAVA pull request #19
Opened 2022-10-27 14:44 UTC by Allody22

This code is not ready, but a have some questions.

2022-10-27 14:47 UTC, Allody22 commented
### _У меня есть парочка вопросов по этой лабе._

**1.** Когда пользователь **подаёт неправильные данные** (требует что-то сделать с ребром/вершиной которой на существует, отрицательные веса кидает), то лучше кидать исключение или, например, сделать пустой return из функции?

**2.** У меня есть класс вершины, у которых есть поля имени. А в самом графе я делаю мап какого-то ключа на эти самые вершины. Вот и получается, что у меня тогда есть отображение, в котором по факту два раза присутствует имя этой самой вершины, то есть Map< T(name of the vertex), Vertex<T>(в котором есть поля имени вершины)>. Как-то немного странно получается, как мне кажется. Можете сказать, нормальная ли эта ситуация.

**3.** А еще я думал, передавать в конструкторы матрица не в обычном двумерном представлении, а в row-major, это, как нам рассказывал лектор на си в прошлом году, куда выгоднее по памяти. Имеет ли это вообще смысл?

2022-10-31 13:40 UTC, Allody22 commented
Я уже почти закончил, завтра в обед точно загружу рабочую программу, дописываю все тесты красиво

2022-10-31 14:04 UTC, Allody22 commented
Right now it looks like this, but I need to write a lot of tests that will check my code (and doesn't want to build lol)

2022-10-31 16:44 UTC, shadrina commented
1. Надо бросать соответствующее исключение, как раз для этого они и сделаны.
2. Да, вполне.
3. Кстати хороший вопрос. В Java мультимерный массив - это массив массивов, и соответственно его фрагменты могут быть разбросаны по разным кускам памяти. Хранить все это линейно, конечно, эффективнее, но, думаю, сильно испортит читаемость. Поэтому в рамках этого курса и этой задачи, давай пользоваться тем, что предоставляет язык вне зависимости от его memory layout.

2022-11-01 03:14 UTC, Allody22 commented
Я в комментариях напишу по какому принципу такие **row-major матрицы** работают, всё должен быть понятно. Немного жалко просто терять их, учитывая что я нормально времени потратил, чтобы там всё хорошо работало. Если все равно не понравится, то я заменю их

2022-11-01 13:15 UTC, Allody22 commented
Я постарался максимально сохранить удобные для пользователя условия и близкие к оригинальным. То есть, если в граф подаётся матрица смежности и имена вершин, то в граф передается (а в инпут файле) **ТОЛЬКО** матрица смежности и  **ТОЛЬКО** названия вершин, без информации и количестве вершин или количестве рёбер. Так было немного сложнее и интереснее, пришлось поискать информацию о различных парсерах массивов,но зато всё хорошо работает при таких условиях

2022-11-01 13:45 UTC, Allody22 commented
not enough coverage(((

2022-11-02 07:10 UTC, shadrina requested changes

2022-11-02 07:10 UTC, shadrina commented on Task_1_2_3/src/main/java/ru/nsu/mbogdanov2/Graph.java
> +        for (Map.Entry<T, Vertex<T>> entry : vertexes.entrySet()) {
var

2022-11-02 07:10 UTC, shadrina commented on Task_1_2_3/src/test/java/ru/nsu/mbogdanov2/GraphTest.java
> +        InputStream file =
try with resources

2022-11-02 15:37 UTC, Allody22 commented on Task_1_2_3/src/test/java/ru/nsu/mbogdanov2/GraphTest.java
> +        InputStream file =
fixed

2022-11-05 11:09 UTC, Allody22 commented
Странная штука, я уже 2 раза запрашиваю повторный реквест, а он пропадает и приходится запрашивать опять, хотя от вас никаких сообщений или изменений, вроде, не было

2022-11-07 10:54 UTC, shadrina approved these changes

2022-11-07 10:54 UTC, shadrina commented on Task_1_2_3/src/main/java/ru/nsu/mbogdanov2/Edge.java
> +public class Edge<T> {
Это эквивалентно `record Edge(...)`

2022-11-07 10:54 UTC, shadrina commented on Task_1_2_3/src/main/java/ru/nsu/mbogdanov2/Graph.java
> +    private final int inf = Integer.MAX_VALUE;
Это константа. Их обычно пишут в начале файла и делают static final. А еще все буквы названия в верхнем регистре.

```
private static final int INF = ...;
```

2022-11-07 12:29 UTC, Allody22 commented on Task_1_2_3/src/main/java/ru/nsu/mbogdanov2/Graph.java
> +    private final int inf = Integer.MAX_VALUE;
Знаю про верхний регистр, но ревьюв дог ужасно жалуется когда видит идёт больше 2 заглавных букв рядом. Я сам сначала писал нормально IMF

2022-11-07 18:34 UTC, shadrina commented on Task_1_2_3/src/main/java/ru/nsu/mbogdanov2/Graph.java
> +    private final int inf = Integer.MAX_VALUE;
Скорее всего потому что забыл static и ревьюдог не воспринимает это как константу. И правильно делает

2022-11-08 01:57 UTC, merged