Task_1_1_1
Allody22/OOP_JAVA pull request #2
Opened 2022-09-15 13:07 UTC by Allody22

сейчас наверное опять ничего не соберется.....

2022-09-15 15:01 UTC, Allody22 commented
YEEEES, I'VE DONE THIS

2022-09-20 10:55 UTC, shadrina requested changes

2022-09-20 10:55 UTC, shadrina commented on Task_1_1_1/src/main/java/HeapSort.java
> +/**
Пакет бы какой-нибудь.

2022-09-20 10:55 UTC, shadrina commented on Task_1_1_1/src/main/java/HeapSort.java
> +     *   5 (3)  1 (4)
Это вы в интернете где-то такой коммент подсмотрели? У другого студента увидела -- похвалила за оригинальность...

2022-09-20 10:55 UTC, shadrina commented on Task_1_1_1/src/test/java/HeapSortTests.java
> +     * Test number 2 for empty array.
Номер теста писать не нужно ни в комментарии, ни в названии теста. Лучшим неймингом будет суть: `emptyArrayTest()` или `testWithEmptyArray()`, как угодно.

2022-09-20 10:55 UTC, shadrina commented on Task_1_1_1/src/test/java/HeapSortTests.java
> +}
Давай еще тест со случайными числами. См. `java.util.Random`

2022-09-20 10:56 UTC, shadrina requested changes

2022-09-20 10:56 UTC, shadrina commented on .github/google_checks.xml
> +  "https://checkstyle.org/dtds/configuration_1_3.dtd">
А зачем в PR на первую задачу какие-то изменения в этом файле?

2022-09-20 11:05 UTC, Allody22 commented on Task_1_1_1/src/main/java/HeapSort.java
> +     *   5 (3)  1 (4)
Ну, вообще в интернете по первой ссылке, а еще попросил у одногруппника его репозиторий, чтобы нормально собрать проект и оформить комментарии для reviewdog. С таким вариантов reviewdog не жаловался, поэтому оставил его

2022-09-20 11:13 UTC, Allody22 commented on .github/google_checks.xml
> +  "https://checkstyle.org/dtds/configuration_1_3.dtd">
Я пытался установить гуглстайл чек так,чтобы он работал в самом IntelliJ, но для этого пришлось ставить другой файл (может я, конечно, не правильно что-то делал, но с данным не получалось), а потом с другим файлом у меня всё на гитхабе сломалось, в итоге я очень много раз туда-сюда всё менял и получилось вот так.

2022-09-20 11:18 UTC, Allody22 commented on Task_1_1_1/src/test/java/HeapSortTests.java
> +     * Test number 2 for empty array.
Я до этого писал подобные названия, но reviewdog жаловался, возможно, ошибка была в том, что я писал их названия с большой буквы или что-то подобное, потому что сейчас спокойно исправилось

2022-09-20 12:26 UTC, Allody22 commented on Task_1_1_1/src/test/java/HeapSortTests.java
> +}
Добавил тест со случайными числами. Почему-то эта проверочная собака жалуется, что в строчке
`public void randomArrayTest() {` нету пробела перед {. Я перепробовал кучу вариантов с пробелами с разных сторон, но ему всё еще не нравится. Не знаю в чём дело

2022-09-20 13:17 UTC, shadrina commented on Task_1_1_1/src/test/java/HeapSortTests.java
> +}
Так он же ругается на отсутствие пробела в 60 строке с `for`'ом

2022-09-20 13:18 UTC, shadrina commented
Выглядит подозрительно... 🤔 
<img width="541" alt="image" src="https://user-images.githubusercontent.com/29809312/191268044-f27ed4fe-7450-4e8d-a4c7-2c14dfec5939.png">

2022-09-20 13:59 UTC, Allody22 commented
> Выглядит подозрительно... 🤔 <img alt="image" width="541" src="https://user-images.githubusercontent.com/29809312/191268044-f27ed4fe-7450-4e8d-a4c7-2c14dfec5939.png">

Блин, ну у меня просто было куча проверок с одинаковыми результатами и они занимали много места, я их удалил, чтобы тут был было чуть почище. Могу в следующий раз такого не делать, если это важно

2022-09-20 14:57 UTC, Allody22 commented on Task_1_1_1/src/main/java/HeapSort.java
> +/**
Так, ну теперь все пакеты должны быть

2022-09-21 07:19 UTC, shadrina requested changes
- Надо заигнорить или убрать папку `.idea` в корне проекта
- В скрипте не хватает команды для исполнения jar'а (команда `java`)

2022-09-21 07:19 UTC, shadrina commented on Task_1_1_1/src/test/java/ru/nsu/mbogdanov2/HeapSortTests.java
> +        int []actual = HeapSort.heapSort(new int[] {1, 2, 3, 4});
Что-то не так с пробелами рядом со скобками массива (здесь и в нескольких местах ниже)

2022-09-21 13:10 UTC, Allody22 commented on Task_1_1_1/src/test/java/ru/nsu/mbogdanov2/HeapSortTests.java
> +        int []actual = HeapSort.heapSort(new int[] {1, 2, 3, 4});
Всё исправлено, всё должен быть хорошо

2022-09-25 15:07 UTC, shadrina approved these changes
Сдано

p.s. Убери, пожалуйста, файл `Task_1_1_1/HeapSort.iml` до мерджа.

2022-09-25 15:16 UTC, merged