Task_1_5_2
Allody22/OOP_JAVA pull request #24
Opened 2022-12-21 14:31 UTC by Allody22

2022-12-22 13:35 UTC, Allody22 commented
Я должен был сказать почему в статик блоке нельзя бросать checked исключения. 
https://stackoverflow.com/questions/2070293/why-doesnt-java-allow-to-throw-a-checked-exception-from-static-initialization-b
Наверное, мне проще оставить ответ на стак оверфлоу. Тут всё по делу

2022-12-22 13:35 UTC, Allody22 commented
Сейчас пофикшу ревьюв дога

2022-12-22 14:23 UTC, Allody22 commented
Reviewdog просит чтобы я не использовал импорты типа ".*", но даже когда я пытаюсь их расписать, джава сама исправляет разные импорты, объединяя в вариант со звездочкой

2022-12-25 06:22 UTC, Allody22 commented
@shadrina может возникнуть 3 вопроса
1) Миша, почему ты не пофиксил всё в reviewdog? 
Reviewdog просит чтобы я не использовал импорты типа ".*", но даже когда я пытаюсь их расписать, джава сама исправляет разные импорты, объединяя в вариант со звездочкой
2) А почему такой маленькие coverage тестов?
В самом классе записной книжке всё статик, поэтому не понятно, как это тестить. Всё проще проверить в мэине обычным запуском 
3)Зачем вообще нужный отдельный класс ArrayOfNotes, если он на 90% совпадает с обычным листом джавы?
Да, вопрос хороший. Библиотека gson не рекомендует использовать list, array и т.п. для работы со своими типами/классами. Поэтому я создаю свой класс-лист, в котором хранятся заметки, чтобы всё хорошо сериализовалось и десериализовалось, а gson чувствовал себя хорошо

2022-12-27 16:41 UTC, shadrina commented
Это замечательно, что ты нашел ссылку на стековерфлоу, но мне важно просто понять, что ты понял.

2022-12-27 17:04 UTC, Allody22 commented
> Это замечательно, что ты нашел ссылку на стековерфлоу, но мне важно просто понять, что ты понял.

Я понял, не хотел писать просто, то на что и так есть ссылка хорошая

2022-12-27 17:11 UTC, shadrina requested changes

2022-12-27 17:11 UTC, shadrina commented on Task_1_5_2/src/main/java/ru/nsu/mbogdanov2/ArrayOfNotes.java
> +    }
У тебя `size` почему-то не приватный.

2022-12-27 17:11 UTC, shadrina commented on Task_1_5_2/src/main/java/ru/nsu/mbogdanov2/ArrayOfNotes.java
> +        return false;
Stream API please

2022-12-27 17:11 UTC, shadrina commented on Task_1_5_2/src/main/java/ru/nsu/mbogdanov2/NoteBook.java
> +                try (FileWriter writer = new FileWriter(notes)) {
Writer

2022-12-28 04:14 UTC, Allody22 commented on Task_1_5_2/src/main/java/ru/nsu/mbogdanov2/ArrayOfNotes.java
> +    }
Не знаю почему так получилось, исправил

2023-01-22 13:35 UTC, merged