Task_2_1_1
Allody22/OOP_JAVA pull request #26
Opened 2023-02-13 09:05 UTC by Allody22

@shadrina прошлая ветка совсем плохая была. Как-то плохо всё запушил, вот новая хорошая (надеюсь (вроде))

2023-02-13 09:14 UTC, Allody22 commented
Уже писал об этом в прошлом пул реквесте, но так как я сам его уничтожил, сейчас лучше еще раз напишу
Ревьювдог жалуется на пару ошибки, некоторые из них полные ерунда (я даже писал об этом уже)
Просит импорты, заканчивающиеся на * заменить на конкретные модули. Мне джава такое сделать даже не даёт и автоматически их превращает в общие, заканчивающиеся на *. В репорте собаки-проверщика есть конкретные примеры вот этого 
Не знаю есть ли у других ребят в группе такие проблемы, но бред ведь какой-то

2023-02-17 15:34 UTC, Allody22 commented
@shadrina, в общем осталась одна жалоба от reviewdog`а: **Using the '.*' form of import should be avoided - java.awt.*.** 
Я уже разрешил, не объединять импорты с *, даже если там скрывается 500 импортов!!!! Но тут все равно не работает
Функция такая в настройках легко ставится, вот [пруфы](http://www.stateofmind.ru/java/kak-zapretit-v-intellij-idea-obedinenie-importov-v.html)
Так что считаю всё хорошо, сейчас еще отвечу на вопросы, которые получил во вторник

2023-02-18 13:06 UTC, Allody22 commented
Главный плюс threadPool: Не нужно создать каждый раз thread для какой-то задачи, то есть обычно для threadPool делают список каких-то задачи, где после выполнения одной задачи, не нужно будет опять создавать thread для следующей, т.к. в threadPool все потоки постоянно активины ==> не нужно создавать каждый раз новые потоки (а их создание операция вообще не дешевая) ==> экономия времени и ресурсов 
Как главный минус можно выделить, что у нас нет контроля за состоянием и приоритетами потоков внутри threadPool, ну и threadPool не имеет смысла для работы с какой-то 1 задачей, то есть там, где хватит одного потока

2023-02-21 08:17 UTC, shadrina requested changes

2023-02-21 08:17 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/mbogdanov2/PrimeSearch.java
> +        }
Nullability annotations please

2023-02-21 08:17 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/mbogdanov2/PrimeSearch.java
> +    }
В отдельный класс либо удалить и использовать референс на второй такой статик

2023-02-21 08:17 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/mbogdanov2/PrimeSearchWithStreams.java
> +        }
Аналогично

2023-02-21 08:17 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/mbogdanov2/PrimeSearchWithStreams.java
> +        return intStream.parallel().anyMatch(number -> !primeCheck(number));
Можно заинлайнить intStream

2023-02-21 08:17 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/mbogdanov2/PrimeSearchWithThread.java
> +        }
Аналогично

2023-02-21 08:17 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/mbogdanov2/PrimeSearchWithThread.java
> +        if (flag) {
Называй как есть

2023-02-21 08:17 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/mbogdanov2/PrimeSearchWithThread.java
> +    private Deque<Integer> deque;
Давай попробуем разделить обычный список, который будет "распараллеливаться" путем разделения на части

2023-02-27 17:07 UTC, vhlebnikov commented
> Уже писал об этом в прошлом пул реквесте, но так как я сам его уничтожил, сейчас лучше еще раз напишу Ревьювдог жалуется на пару ошибки, некоторые из них полные ерунда (я даже писал об этом уже) Просит импорты, заканчивающиеся на * заменить на конкретные модули. Мне джава такое сделать даже не даёт и автоматически их превращает в общие, заканчивающиеся на *. В репорте собаки-проверщика есть конкретные примеры вот этого Не знаю есть ли у других ребят в группе такие проблемы, но бред ведь какой-то

https://stackoverflow.com/questions/3348816/intellij-never-use-wildcard-imports

2023-02-28 08:04 UTC, shadrina commented
Как в итоге поменялся график при смене алгоритма? Хочется каких-то выводов

2023-02-28 10:00 UTC, Allody22 commented
@shadrina  Хотел об этом на паре рассказать, но, как это уже понятно, внезапно не получилось придти, поэтому напишу вот тут.
В общем мой алгоритм отлично работал, очень маленькие различия с алгоритмом, в котором просто разбивается массив на кол-во тредов. При одинаковом количестве тредов, эти два алгоритма не отстают друг от друга и отлично работают.
***То есть всё хорошо работало и работает, никаких проблем***

2023-03-08 11:24 UTC, Allody22 commented
!

2023-03-09 13:32 UTC, Allody22 commented
@shadrina Настя, я всё сделал, даже часть второй лабы, можно мне фидбек про этот пулреквест :pray::pray::purple_heart:

2023-03-11 11:45 UTC, shadrina commented
Миша, я про тебя помню. Твой дедлайн не пострадает, просто я сама в дедлайнах

2023-03-11 12:00 UTC, Allody22 commented
> Миша, я про тебя помню. Твой дедлайн не пострадает, просто я сама в дедлайнах

Понимаю, тут ведь правда осталось заапрувить это, а я с чистой совестью второй пулреквест сделаю (мне так куда спокойней просто)

2023-03-12 17:24 UTC, shadrina requested changes
Мы здесь про "сдать побыстрее" или все-таки про качество и обучение? Вы в первую очередь заинтересованы в тщательной проверке по профильному предмету.

2023-03-12 17:24 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/mbogdanov2/PrimeSearchWithThreadsBySeparation.java
> +        Arrays.stream(threads).forEach(myThread -> {
Стримы, конечно, хорошо, но и перебарщивать с ними не надо. Тут гораздо более органично смотрелся бы обычный `for`.

2023-03-12 17:24 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/mbogdanov2/PrimeSearchWithThreadsBySeparation.java
> +    public boolean search(int threadsNumber, boolean turnOnThreadsNumber, List<Integer> primeList) {
Я верно понимаю, что весь этот метод идет на замер времени?

2023-03-12 17:24 UTC, shadrina commented on Task_2_1_1/src/test/java/ru/nsu/mbogdanov2/speed/PerformanceTest.java
> +            time = System.nanoTime() - time;
То, о чем я говорила выше, измерение некорректно, потому что оно в том числе учитывает время на разделение на "подсписки", которое ты никак не оптимизировал. Эту операцию надо вынести.

2023-03-12 17:24 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/mbogdanov2/PrimeSearchWithThread.java
> +        }
А где nullability аннотации? Резолвит дискуссию тот, кто открыл.

2023-03-12 17:24 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/mbogdanov2/PrimeSearchWithStreams.java
> +        }
Почему не исправлено и зарезолвлено?

2023-03-12 18:14 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/mbogdanov2/PrimeSearchWithThreadsBySeparation.java
> +            throw new NullPointerException();
Тут `NullPointerException` не в тему, `IllegalStateException`

2023-03-12 18:17 UTC, shadrina commented on Task_2_1_1/src/test/java/ru/nsu/mbogdanov2/speed/PerformanceTest.java
> +            time = System.nanoTime() - time;
Не, фигня, вычисление подсписков даже не линейно. Ничего выносить не надо

2023-03-13 05:09 UTC, Allody22 commented
> Мы здесь про "сдать побыстрее" или все-таки про качество и обучение? Вы в первую очередь заинтересованы в тщательной проверке по профильному предмету.
Понимаю, прости, немного не то сказал
Сейчас буду исправлять новые ошибки

2023-03-13 06:20 UTC, Allody22 commented
Ладно, наконец-то все импорты отсортированы. 
Видимо у меня какие-то плохие настройки, потому что каждый раз абсолютно всё сортируется неправильно

2023-03-13 17:25 UTC, shadrina approved these changes
Я уж не знаю, что концептуально изменилось, но теперь график больше похож на правду. 

А с импортами выключите уже это в конфиге ревьюдога, раз так мешает жить. Но только через отдельный PR и с моим апрувом.

2023-03-13 17:25 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/mbogdanov2/PrimeSearch.java
> +    public boolean search(int @NotNull [] array) {
Аннотация ставится до типа

2023-03-13 17:33 UTC, Allody22 commented on Task_2_1_1/src/main/java/ru/nsu/mbogdanov2/PrimeSearch.java
> +    public boolean search(int @NotNull [] array) {
Я буду счастлив узнать как выключить эту настройку в ревьювдоге

2023-03-13 17:33 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/mbogdanov2/PrimeSearch.java
> +    public boolean search(int @NotNull [] array) {
Ой, точно, он так захочет ставить @NotNull на тип элемента массива, а не на весь массив.
Кошмар, тогда так конечно оставляй.

2023-03-13 17:33 UTC, merged

2023-03-13 17:36 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/mbogdanov2/PrimeSearch.java
> +    public boolean search(int @NotNull [] array) {
https://github.com/Allody22/OOP_JAVA/blob/master/.github/google_checks.xml