Task_2_2_1
Allody22/OOP_JAVA pull request #30
Opened 2023-03-14 03:51 UTC by Allody22

2023-03-14 04:01 UTC, Allody22 commented
﻿# Pizzeria application (возможно это лучше в readme написать, но пусть будет тут)
***Не знаю получится ли у меня время взять для показывания лабораторной, поэтому тут всё напишу хорошо (тесты в процессе, ревьювдог в процессе, пожалуйста, пока смотреть только на сам код/основную идею), а вообще уже всё время заняли***
### У нас есть такие роли, участвующие в этой лабе
- baker - повар (он же employee, producer, user)
-  courier - курьер (он же employee, user)
- customer - покупатель, то есть тот кто заказывает (он же producer)
Из названий всё должно быть примерно понятно

###Немного про свойства/особенности моей реализации
1) Пиццерия работает какое-то время, указанное в специальном классе (ну не работает ведь бесконечно в реальности пиццерия). А пока пиццерия работает, она получает заказы
2)Пиццерия работает, пока пулы потоков пекарей и курьеров не завершились
3)Возможности людей/завода ограничены, поэтому у очереди есть ограничение по размеру склада, багажника, кол-во пекарей
4)Конкретно не указано, как использовать working experience, поэтому у пекарей есть максимальное время готовки, до которого мы находится ближайший рандомный лонг, а потом делим на опыт работы. Ведь заказы бывают разной сложности, а таким образом опыт работы реально на что-то влияет
5)Еще есть максимальное время бронирования, доставки заказа, бронирования заказа. Время каждого из них я постарался более-менее логично расположить
to be continued.....

2023-03-16 03:37 UTC, Allody22 commented
> # Pizzeria application (возможно это лучше в readme написать, но пусть будет тут)
> _**Не знаю получится ли у меня время взять для показывания лабораторной, поэтому тут всё напишу хорошо (тесты в процессе, ревьювдог в процессе, пожалуйста, пока смотреть только на сам код/основную идею). А вообще уже всё время на сегодня на пару заняли....**_
> 
> ### У нас есть такие роли, участвующие в этой лабе
> * baker - повар (он же employee, producer, user)
> * courier - курьер (он же employee, user)
> * customer - покупатель, то есть тот кто заказывает (он же producer)
>   Из названий всё должно быть примерно понятно
> 
> ### Немного про свойства/особенности моей реализации
> * Пиццерия работает какое-то время, указанное в специальном классе (ну не работает ведь бесконечно в реальности пиццерия). А пока пиццерия работает, она получает заказы
> * Пиццерия работает, пока пулы потоков пекарей и курьеров не завершились
> * Возможности людей/завода ограничены, поэтому у очереди есть ограничение по размеру склада, багажника, кол-во пекарей
> * Конкретно не указано, как использовать working experience, поэтому у пекарей есть максимальное время готовки, до которого мы находится ближайший рандомный лонг, а потом делим на опыт работы. Ведь заказы бывают разной сложности, а таким образом опыт работы реально на что-то влияет
> * Еще есть максимальное время бронирования, доставки заказа, бронирования заказа. Время каждого из них я постарался более-менее логично расположить
>   Диаграмму классов, принципы solid, ревьюв дога, тесты, напишу сегодня-завтра
>   to be continued.....

## New info (16.03/2023)
- Тестов для класса PizzeriaApplication не будет, это класс для простого запуска самой программы
- Про класс PizzeriaReader тоже не уверен, ведь это по факту класс, чтобы читать JSON
- Добавлена диаграмма классов

2023-03-21 04:12 UTC, Allody22 commented
## New info (21.03/2023)
- Тесты я сделал для всего, чего смог, это, вроде, окончательный код (по крайней мере по кол-ву классов/файлов)
## Про solid 
- Single Responsibility Principle:  каждый класс имеет одну ответственность - отдельный классы под JSON для пекарей, курьеров и т.п., отдельные классы для считывания этого джейсона, запуска приложения и логики приложения
- Open/Closed Principle: классы открыты для расширения но закрыты для изменения - в пакете participants два главных интерфейса от которых наследуются другие модели, если есть желание, любая модель подходит под один из этих интерфейс и реализует соответствующий метод. Есть и абстрактный класс Employee необходимый для работников, сам метод work можно переопределить в зависимости от задачи какой-то модели
- Liskov Substitution Principle: ну каждый объект может быть заменён на экземпляры своих подтипов без изменения корректности выполнения программы.  Довольно много написал в прошлом принципе об этом: что от чего наследуется, всё это сделано исходя из обычной логики. Думаю, всё понятно
- Interface Segregation Principle: модули более высокого уровня не должны зависеть от модулей более низкого уровня, а оба типа модулей должны зависеть от абстракций.
- Dependency Inversion Principle:  Модули верхнего уровня не должны зависеть от модулей нижнего уровня. В общем-то последние 2 принципа очень похоже. Как можно больше используем абстракции, чтобы изменять зависимые друг от друга классы было проще. 
to be continued....

2023-03-21 04:13 UTC, Allody22 commented
Я еще не могу повторную проверку запросить, потому что никакие ресолвов не было. Можно я тэгну тогда на всякий случай @shadrina

2023-03-21 04:59 UTC, Allody22 commented
А вообще я щас сижу на паре с больным горлом и утопаю в соплях (простите за подробности) и не очень понимаю, стоит ли мне идти еще на ооп или нет. Игорь тоже у нас точно заболел, наша группа потихоньку заболевает кажется

2023-03-21 07:18 UTC, shadrina commented
Если болеете, идите лечитесь. Проверю удаленно

2023-03-23 11:50 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/json/BakerJson.java
> +    public int workingExperience;
Почему все публичное?

2023-03-23 11:50 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/json/CourierJson.java
> +    public int bagCapacity;
Аналогично. Если поля публичные, геттеры теряют смысл

2023-03-23 11:50 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/json/JsonReader.java
> +    public BufferedReader reader;
И снова публичный

2023-03-23 11:50 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/MyBlockingDequeue.java
> +public class MyBlockingDequeue<T> {
"Deque".

2023-03-23 11:50 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/MyBlockingDequeue.java
> +    private final int size;
Это что-то типа максимального размера? Почему оно final?

2023-03-23 11:50 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/PizzeriaLaunch.java
> +            System.exit(1);
Ты же знаешь, что оно убивает все потоки и JVM, а не только текущий?

2023-03-23 11:50 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/PizzeriaLaunch.java
> +            System.exit(1);
Так задумано?

2023-03-23 15:11 UTC, Allody22 commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/MyBlockingDequeue.java
> +public class MyBlockingDequeue<T> {
Ахах, не знаю почему так получилось, я был уверен что там два раза ue в конце пишется, даже в проекте так буквально позавчера писал. Исправлю

2023-03-23 15:18 UTC, Allody22 commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/PizzeriaLaunch.java
> +            System.exit(1);
Ну да, о работе пиццерии не может быть и речи, если pizzeriaReader равен нулу. Я подумал, что самое логичное это сделать тут exit(1)

2023-03-24 14:20 UTC, Allody22 commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/json/CourierJson.java
> +    public int bagCapacity;
А, ну, вообще мне просто пригодилось обращаться к этим полям только в тестах и я решил их сделать паблик, чтобы сравнивать в тестах. Стоит гетеры написать, да, немного поленился и не подумал можно сказать

2023-03-24 14:21 UTC, Allody22 commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/json/CourierJson.java
> +    public int bagCapacity;
И это ко всем классам в json пакете относится

2023-03-24 15:03 UTC, Allody22 commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/PizzeriaLaunch.java
> +            System.exit(0);
Если честно, не особо понял что именно из этого могу не писать и почему

2023-03-24 15:08 UTC, Allody22 commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/json/JsonReader.java
> +        }
Оно падает в классе PizzeriaLaunch в таком случае, там об этом как раз ниже есть conversation

2023-03-24 15:11 UTC, Allody22 commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/json/JsonReader.java
> +        }
Хотя нам в эту среду Мокин на лекции по проекту рассказывал как раз о таком ситуациях. То что надо сразу падать, если получается null в важном поле, а не тащить это с собой до важного момента, даже привёл пару своих примеров из практики. Перенесу необходимую часть из PizzeriaLaunch сюда, а там это уберу тогда

2023-03-24 15:13 UTC, Allody22 commented
Остальные вопросы завтра посмотрю, по этим всё более-менее понятно

2023-03-26 15:53 UTC, Allody22 commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/MyBlockingDequeue.java
> +    private final int size;
Да, что-то типа максимального размера. Размер склада например, у нас же есть какой-то один фиксированный размер и мы не можем ничего с ним сделать (он не уменьшается и не увеличивается). Если размер очереди (ну то есть объектов в очереди) равен этой переменной сайз, то мы ждём пока очередь освободится (например со склада заберут заказы). В методе put это написано

2023-03-26 15:55 UTC, Allody22 commented
Я кстати не очень понимаю, должен ли я нажимать resolve conversation, если я как бы ответил на комментарий/вопрос. Я ведь ничего не исправил, но написал почему не надо исправлять. Сейчас нажимаю на resolve conversation, если так не надо, то не буду больше

2023-03-26 16:07 UTC, Allody22 commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/MyBlockingDequeue.java
> +    }
Привет! Я хотел бы извиниться за то, что не сделал метод contains synchronized. Я понимаю, что это могло привести к проблемам в работе программы. Я обещаю быть более внимательным в будущем и убедиться, что все методы, которые должны быть synchronized, будут такими. Кроме того, я хочу отметить, что я использую этот метод только в тестах. Извините за неудобства!

2023-03-26 16:08 UTC, Allody22 commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/MyBlockingDequeue.java
> +    }
Это написала нейросеть, но именно то что я хотел сказать

2023-03-28 08:20 UTC, shadrina requested changes

2023-03-28 08:20 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/model/people/Employee.java
> +    public boolean runEmployee;
Зачем она `public`? Может доступиться любой из любого потока.

2023-03-28 08:20 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/PizzeriaReader.java
> +                .collect(Collectors.toCollection(ArrayList::new));
`.toList()`

2023-03-28 08:20 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/PizzeriaReader.java
> +                .collect(Collectors.toCollection(ArrayList::new));
Аналогично

2023-03-28 08:20 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/PizzeriaLaunch.java
> +            System.exit(0);
Лучше всех заджойнить, это честнее

2023-03-28 08:20 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/PizzeriaReader.java
> +        }
`Thread.sleep` хотя бы. Тут кушается процессорное время.

2023-03-28 10:32 UTC, Allody22 commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/PizzeriaReader.java
> +        }
Если просто добавить 
```
try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
```
То вылезает предупреждение "Call to 'Thread.sleep()' in a loop, probably busy-waiting "
Интернет мне объяснил, что это означает, что 
***Когда вызывается Thread.sleep() в цикле, программа не выполняет никакой работы, пока не проходит время ожидания, и вместо этого простаивает, занимая процессорное время, что называется "busy-waiting". Это может привести к значительному потреблению процессорного времени и ухудшить производительность программы.

Чтобы исправить это предупреждение, можно использовать более эффективный способ ожидания, такой как использование семафоров, мониторов или блокировок. Эти методы позволяют потокам ждать событий или условий без занятости процессора.***
Ну и этот эффективный метод ожидания, вроде, будет выглядеть вот так
```
while (runPizzeria && !bakersThreadPool.isTerminated() && !couriersThreadPool.isTerminated()) {
    synchronized (this) {
        try {
            wait(100); // Ожидание события в течение 100 миллисекунд
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
```

2023-03-28 10:51 UTC, Allody22 commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/json/JsonReader.java
> +        if (content.equals("")) {
Done

2023-03-28 10:51 UTC, Allody22 commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/model/people/Employee.java
> +    public boolean runEmployee;
Done

2023-03-28 10:51 UTC, Allody22 commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/PizzeriaReader.java
> +                .collect(Collectors.toCollection(ArrayList::new));
Done

2023-03-28 10:51 UTC, Allody22 commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/PizzeriaReader.java
> +                .collect(Collectors.toCollection(ArrayList::new));
Done

2023-03-28 10:51 UTC, Allody22 commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/PizzeriaReader.java
> +        }
Done

2023-03-28 10:51 UTC, Allody22 commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/MyBlockingDeque.java
> +        return deque.size() == 0;
Done

2023-03-31 07:16 UTC, Allody22 commented
Ааааа, забыл плюсик перенести, вечером залью видео с демонстрацией работы пиццерии под приятную музыку

2023-03-31 07:25 UTC, Allody22 commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/pizzeria/PizzeriaLaunch.java
> +            System.exit(0);
done (как долго пришлось искать где находится эта ветка)

2023-03-31 14:54 UTC, Allody22 commented
Вот ссылка на [видео](https://disk.yandex.ru/i/pXjtQf0W-0blVQ) с демонстрацией работы лабы
Я параллельно включил 24 часа челендж в пиццерии от влада а4, но почему-то захватился только экран с идешкой, поэтому не надо удивляться тому, что порой я говорю про влада а4
Ну всё работает, всё хорошо, спасибо за внимание (надеюсь ссылка будет хорошо работать

2023-04-04 12:41 UTC, Allody22 commented
@shadrina вот такой вариант добавил, погуглил и нашёл CountDownLatch, штука вроде крутая и ускоряет/упрощает всю работу для программы

2023-04-09 12:36 UTC, shadrina approved these changes
Вот теперь все хорошо 👍

2023-04-09 12:36 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/model/people/Baker.java
> +            flag = false;
Вместо вот этого флага можно было бы точно так же, как выше, вызвать `Thread.currentThread().interrupt()`, а из вышестоящего вызова проверить `isInterrupted()`

2023-04-09 12:36 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/model/people/Employee.java
> +    }
runEmployee можно выставить прямо при объявлении филда, а примитивный конструктор тоже можно генерить с помощью lombok

2023-04-09 12:37 UTC, shadrina commented
В твоем случае `CountDownLatch` как раз играет роль того, на чем можно заблокироваться. Хорошее решение.

2023-04-09 12:44 UTC, merged

2023-04-09 12:54 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/model/people/Baker.java
> +            flag = false;
Ну вот это можно было бы и поправить...

2023-04-09 13:05 UTC, Allody22 commented on Task_2_2_1/src/main/java/ru/nsu/mbogdanov2/model/people/Baker.java
> +            flag = false;
Пофксил это в мейне